services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: GraphQLSample
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet" ]
      interval: 1s
      timeout: 2s
      retries: 5

  graphql_sample:
    image: graphql_sample:latest
    build:
      context: .
      dockerfile: ./src/Web/Dockerfile
    container_name: graphql_sample
    ports:
      - "4000:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production 
      ServerUrl: "https://sepfrd.com"
      ClientUrl: "https://sepfrd.com"
      GraphQLOptions__MaxPageSize: 100
      GraphQLOptions__ExecutionTimeoutSeconds: 3.0
      GraphQLOptions__MaxFieldCost: 1000.0
      GraphQLOptions__MaxTypeCost: 10000.0
      GraphQLOptions__DefaultResolverCost: 10.0
      GraphQLOptions__IncludeTotalCount: true
      GraphQLOptions__IncludeExceptionDetails: false
      GraphQLOptions__EnforceCostLimits: true
      GraphQLOptions__ApplyCostDefaults: true
      JwtOptions__PrivateKey: "${PRIVATE_KEY}"
      JwtOptions__PublicKey: "${PUBLIC_KEY}"
      JwtOptions__TokenExpirationDurationMinutes: 1440
      MongoDbOptions__ConnectionString: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017"
      MongoDbOptions__DatabaseName: GraphQLSample
      EnableDataSeed: ${ENABLE_DATA_SEED}
