services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: GraphQLSample
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet" ]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 20s
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  graphql_sample:
    image: graphql_sample:latest
    build:
      context: .
      dockerfile: ./src/Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production

      # INTERNAL SERILOG
      InternalSerilog__MinimumLevel__Default: Information
      InternalSerilog__MinimumLevel__Override__Microsoft: Warning
      InternalSerilog__MinimumLevel__Override__System: Warning
      InternalSerilog__WriteTo__0__Name: File
      InternalSerilog__WriteTo__0__Args__path: /app/logs/log-.json
      InternalSerilog__WriteTo__0__Args__rollingInterval: Day
      InternalSerilog__WriteTo__0__Args__rollOnFileSizeLimit: true
      InternalSerilog__WriteTo__0__Args__formatter: Serilog.Formatting.Json.JsonFormatter
      InternalSerilog__WriteTo__1__Name: Console
      InternalSerilog__WriteTo__1__Args__outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
      InternalSerilog__Enrich__0: FromLogContext
      InternalSerilog__Enrich__1: WithMachineName
      InternalSerilog__Enrich__2: WithThreadId

      # MAIN SERILOG
      Serilog__MinimumLevel__Default: Warning
      Serilog__WriteTo__0__Name: MongoDBBson
      Serilog__WriteTo__0__Args__databaseUrl: mongodb://mongodb:27017/GraphQLSample
      Serilog__WriteTo__0__Args__collectionName: Logs
      Serilog__WriteTo__0__Args__cappedMaxSizeMb: 1024
      Serilog__WriteTo__0__Args__cappedMaxDocuments: 50000
      Serilog__WriteTo__0__Args__rollingInterval: Day
      Serilog__WriteTo__0__Args__formatter: Serilog.Formatting.Json.JsonFormatter
      Serilog__Enrich__0: FromLogContext
      Serilog__Enrich__1: WithMachineName

      ApplicationUrl: "${APPLICATION_URL}"
      GraphQLOptions__MaxPageSize: 100
      GraphQLOptions__ExecutionTimeoutSeconds: 3.0
      GraphQLOptions__MaxFieldCost: 1000.0
      GraphQLOptions__MaxTypeCost: 10000.0
      GraphQLOptions__DefaultResolverCost: 10.0
      GraphQLOptions__IncludeTotalCount: true
      GraphQLOptions__IncludeExceptionDetails: false
      GraphQLOptions__EnforceCostLimits: true
      GraphQLOptions__ApplyCostDefaults: true
      JwtOptions__PrivateKey: "${PRIVATE_KEY}"
      JwtOptions__PublicKey: "${PUBLIC_KEY}"
      JwtOptions__Issuer: "https://sepfrd.com"
      JwtOptions__Audience: "https://sepfrd.com"
      JwtOptions__TokenExpirationDurationMinutes: 1440
      MongoDbOptions__ConnectionString: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017"
      MongoDbOptions__DatabaseName: GraphQLSample
      DataSeedOptions__ShouldSeed: ${SHOULD_SEED_DATA}
      DataSeedOptions__ItemsCount: ${SEED_DATA_COUNT}
      DataSeedOptions__ItemsLargeCount: ${SEED_DATA_LARGE_COUNT}
      DataSeedOptions__AdminUsername: ${ADMIN_USERNAME}
      DataSeedOptions__AdminPassword: ${ADMIN_PASSWORD}
      DataSeedOptions__AdminEmail: ${ADMIN_EMAIL}
      DataSeedOptions__UserUsername: ${USER_USERNAME}
      DataSeedOptions__UserPassword: ${USER_PASSWORD}
      DataSeedOptions__UserEmail: ${USER_EMAIL}
    ports:
      - "${APPLICATION_HTTP_PORT}:8080"
    volumes:
      - logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
    driver: local
  logs:
    driver: local

