services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: GraphQLSample
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet" ]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 20s
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  graphql_sample:
    image: graphql_sample:latest
    build:
      context: .
      dockerfile: ./src/Web/Dockerfile
    container_name: graphql_sample
    ports:
      - "${APPLICATION_HTTP_PORT}:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ApplicationUrl: "${APPLICATION_URL}"
      GraphQLOptions__MaxPageSize: 100
      GraphQLOptions__ExecutionTimeoutSeconds: 3.0
      GraphQLOptions__MaxFieldCost: 1000.0
      GraphQLOptions__MaxTypeCost: 10000.0
      GraphQLOptions__DefaultResolverCost: 10.0
      GraphQLOptions__IncludeTotalCount: true
      GraphQLOptions__IncludeExceptionDetails: false
      GraphQLOptions__EnforceCostLimits: true
      GraphQLOptions__ApplyCostDefaults: true
      JwtOptions__PrivateKey: "${PRIVATE_KEY}"
      JwtOptions__PublicKey: "${PUBLIC_KEY}"
      JwtOptions__Issuer: "https://sepfrd.com"
      JwtOptions__Audience: "https://sepfrd.com"
      JwtOptions__TokenExpirationDurationMinutes: 1440
      MongoDbOptions__ConnectionString: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017"
      MongoDbOptions__DatabaseName: GraphQLSample
      DataSeedOptions__ShouldSeed: ${SHOULD_SEED_DATA}
      DataSeedOptions__ItemsCount: ${SEED_DATA_COUNT}
      DataSeedOptions__ItemsLargeCount: ${SEED_DATA_LARGE_COUNT}

volumes:
  mongodb_data:
    driver: local

